authentication/urls.py
from django.urls import path

from authentication.views import (
    DefaultView,
    HomeView,
    LoginView,
    LogoutView,
    RegisterView,
)

app_name = 'authentication'

urlpatterns = [
    path('signup/', RegisterView.as_view(), name="signup"),
    path('home/', HomeView.as_view(), name="home"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('', DefaultView.as_view(), name="default"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('seller.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

seller/urls.py
from django.urls import path
from seller.views import (
    SellerProducts,
    SellerProductsCreateView,
    SellerProductDeleteView,
    SellerProductUpdateView,
    CategorizedSellerProductView,
    CartView,
    DeleteCartView,
    RemoveCartProductView,
)

app_name = "seller"

urlpatterns = [
    path("products/", SellerProducts.as_view(), name="seller_products"),
    path(
        "create-products/",
        SellerProductsCreateView.as_view(),
        name="create_products",
    ),
    path(
        "update-product/<uuid:pk>",
        SellerProductUpdateView.as_view(),
        name="update_product",
    ),
    path(
        "delete-product/<uuid:pk>",
        SellerProductDeleteView.as_view(),
        name="delete_product",
    ),
    path(
        "categorized-seller-products/<str:category>",
        CategorizedSellerProductView.as_view(),
        name="categorized_seller_products",
    ),
    path("add-to-cart/<uuid:id>", CartView.as_view(), name="add_to_cart"),
    path("cart/", CartView.as_view(), name="cart"),
    path("empty-cart/", DeleteCartView.as_view(), name="empty_cart"),
    path(
        "remove-product/<uuid:id>",
        RemoveCartProductView.as_view(),
        name="remove_product"
        ),
]

product/models.py
from django.db import models
import uuid
from authentication.models import User

# Create your models here.


class Category(models.Model):
    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.FloatField()
    image = models.ImageField(
        upload_to='product/images',
        blank=True,
        null=True
        )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['id']

product/forms.py
from django import forms
from product.models import Product


class ProductForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for visible in self.visible_fields():
            visible.required = True
            visible.field.widget.attrs['class'] = 'form-control'

        self.fields['user'].required = False

    class Meta:
        model = Product
        fields = "__all__"

product/views.py
from django.shortcuts import render

# Create your views here.

seller/views.py
from django.shortcuts import render, redirect
from product.models import Product
from django.views.generic.base import TemplateView
from django.views.generic import DeleteView
from django.views.generic import View
from product.forms import ProductForm
from buyer.models import Cart


class SellerProducts(TemplateView):
    # permission_classes = [IsSeller]

    def get(self, request, *args, **kwargs):

        if not request.user.is_authenticated:
            return redirect('/login')

        if request.user.groups.filter(name='seller').exists():
            products = Product.objects.filter(user=request.user)
        else:
            products = Product.objects.all()

        product_form = ProductForm()

        return render(
            request,
            template_name='seller/products.html',
            context={
                "all_products": products,
                "product_form": product_form,
            }
        )


class CategorizedSellerProductView(TemplateView):

    def get(self, request, category, *args, **kwargs):

        if not request.user.is_authenticated:
            return redirect('/login')

        if request.user.groups.filter(name='seller').exists():
            products = Product.objects.filter(
                user=request.user,
                category__name__iexact=category
            )
        else:
            products = Product.objects.filter(category__name__iexact=category)

        product_form = ProductForm()
        category_name = category

        return render(
            request,
            template_name='seller/categorized_seller_products.html',
            context={
                "all_products": products,
                "product_form": product_form,
                "category_name": category_name,
            }
        )


class SellerProductsCreateView(TemplateView):

    def get(self, request, *args, **kwargs):

        if not request.user.is_authenticated:
            return redirect('/login')

        if request.user.groups.filter(name='seller').exists():
            product_form = ProductForm()

            return render(
                request,
                template_name='seller/seller_products.html',
                context={
                    "product_form": product_form,
                }
            )
        else:
            return redirect('/home')

    def post(self, request, *args, **kwargs):

        if not request.user.groups.filter(name='seller').exists():
            return redirect('/home')

        product_form = ProductForm(request.POST, request.FILES)

        if product_form.is_valid():
            # #Commented logic will be used when we don't include
            # #the user field in the form
            # product = product_form.save(commit=False)
            # product.user = request.user
            # product.save()
            product_form.instance.user = request.user
            product_form.save()

            return redirect('/products')

        return render(
            request,
            template_name='seller/seller_products.html',
            context={
                "product_form": product_form,
            }
        )


class SellerProductDeleteView(DeleteView):

    model = Product
    success_url = '/products'
    template_name = 'seller/product_confirm_delete.html'


# class SellerProductUpdateView(UpdateView):
#     model = Product
#     form_class = ProductForm
#     success_url = '/products'
#     template_name = 'seller/product_update.html'
#     context_object_name = 'product_form'

#     def form_valid(self, form):
#         form.instance.user = self.request.user
#         return super().form_valid(form)

#     def get_success_url(self):
#         return redirect('/products')

class SellerProductUpdateView(View):

    def get(self, request, *args, **kwargs):

        if not request.user.is_authenticated:
            return redirect('/login')

        if not request.user.groups.filter(name='seller').exists():
            return redirect('/home')

        product_id = kwargs['pk']
        product_details = Product.objects.get(id=product_id)

        product_form = ProductForm(instance=product_details)

        return render(
            request,
            template_name='seller/product_update.html',
            context={
                "product_form": product_form,

            })

    def post(self, request, pk, *args, **kwargs):

        if not request.user.groups.filter(name='seller').exists():
            return redirect('/home')

        product_details = Product.objects.get(id=pk)
        product_form = ProductForm(request.POST, instance=product_details)

        if product_form.is_valid():
            product_form.instance.user = request.user
            product_form.save()

            return redirect('/products')

        return render(
            request,
            template_name='seller/product_update.html',
            context={
                "product_form": product_form,

            })


class CartView(TemplateView):
    def post(self, request, id, *args, **kwargs):

        if not request.user.groups.filter(name='buyer').exists():
            return redirect('/home')

        cart, created = Cart.objects.get_or_create(user=request.user)
        cart.products.add(id)

        return redirect('/home')

    def get(self, request, *args, **kwargs):
        # cart_products = Cart.objects.filter(user=request.user).values_list(
        #     "products__id", "products__name"
        # )
        # cart = Cart.objects.get(user=request.user).products.all()

        if not request.user.groups.filter(name='buyer').exists():
            return redirect('/home')

        cart = Cart.objects.prefetch_related("products").filter(user=request.user).first()
        if cart:
            cart_products = cart.products.all()
        else:
            cart_products = None

        return render(
            request,
            template_name="seller/cart.html",
            context={
                "cart_products": cart_products,
            },
        )


class RemoveCartProductView(View):

    def get(self, request, id, *args, **kwargs):

        if not request.user.groups.filter(name='buyer').exists():
            return redirect('/home')

        product = Product.objects.filter(id=id).first()

        cart = Cart.objects.filter(products=product).first()

        cart.products.remove(id)

        return redirect('/cart')


class DeleteCartView(View):

    def post(self, request, *args, **kwargs):

        if not request.user.groups.filter(name='buyer').exists():
            return redirect('/home')

        cart = Cart.objects.get(user=request.user)
        cart.delete()

        return redirect("/cart")

templates/seller/cart.html
{% extends 'base.html' %}

{% block body %}
<div class="container">

    <div class="row">
        <div class="col-10">

        </div>
        <div class="col-2 mt-5">
            {% if cart_products %}
                <form method="POST" action="{% url 'seller:empty_cart' %}" class="mx-1 mx-md-4" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="submit" value="Empty Cart" name="Add Product" class="btn btn-danger">
                </form>
            {% endif %}
        </div>
    </div>

    <div class="row">
    <div class="text-center mb-5 mt-5"><h1>{{request.user.first_name}}'s Cart</h1></div>
        {% for product in cart_products %}
            <div class="col-4">
                <div class="card mb-5" style="width: 18rem;">
                    <img src="{{ MEDIA_ROOT }}{{product.image.url}}" class="card-img-top" alt="..." width="150" height="250">
                    <div class="card-body text-center">
                        <h5 class="card-title">{{ product.name}}</h5>
                        <p class="card-text">Rs {{ product.price }}</p>
                        <a class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#test{{product.id}}" >View</a>
                    </div>
                </div>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="test{{product.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Product Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-12">
                                    <img src="{{ MEDIA_ROOT }}{{product.image.url}}" class="card-img-top" alt="..." width="150" height="250">
                                    <h4>{{ product.name}}</h4>
                                    <p>{{ product.description}}</p>
                                    <p>Category :{{ product.category }}</p>
                                    <h5 class="mt-2">Price: Rs {{ product.price}}</h5>
                                    <a href="{% url 'seller:remove_product' product.id %}" class="btn btn-danger mt-3">Remove From Cart</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
                </div>
            </div>
        {% endfor %}        
    </div>
    {% if cart_products %}
        <div class="text-center">
            <button class="btn btn-warning btn-lg text">Proceed To CheckOut</button>
        </div>
    {% else %}
        <h5 class="text-center">Your Cart is Empty! Please add some products to CheckOut</h5>
    {% endif %}
</div>

{% endblock body %}

templates/seller/categorized_products.html
{% extends 'base.html' %}

{% block body %}
<a href="{% url 'seller:create_products' %}" class="btn btn-outline-primary m-3">Add Product</a>
<div class="container">

    <div class="row">
        <div class="col-10">

        </div>
        <div class="col-2">
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                  Filter
                </button>
                <a class="btn btn-secondary" href="{% url 'seller:seller_products' %}">Clear</a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  <li><a class="dropdown-item" href="{% url 'seller:categorized_products' 'electrical appliances' %}">Electrical Appliances</a></li>
                  <li><a class="dropdown-item" href="{% url 'seller:categorized_products' 'clothes' %}">Clothes</a></li>
                  <li><a class="dropdown-item" href="{% url 'seller:categorized_products' 'footwares' %}">Footwares</a></li>
                  <li><a class="dropdown-item" href="{% url 'seller:categorized_products' 'home appliances' %}">Home Appliances</a></li>
                </ul>
              </div>
        </div>
    </div>

    <div class="row">
    <div class="text-center mb-5 mt-5"><h1>{{ category_name }}</h1></div>
        {% for product in all_products %}
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{ MEDIA_ROOT }}{{product.image.url}}" class="card-img-top" alt="..." width="150" height="250">
                    <div class="card-body text-center">
                        <h5 class="card-title">{{ product.name}}</h5>
                        <p class="card-text">Rs {{ product.price }}</p>
                        <a class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#test{{product.id}}" >View</a>
                    </div>
                </div>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="test{{product.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Product Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-8">
                                    <img src="{{ MEDIA_ROOT }}{{product.image.url}}" class="card-img-top" alt="..." width="150" height="250">
                                    <h4>{{ product.name}}</h4>
                                    <p>{{ product.description}}</p>
                                    <p>Category :{{ product.category }}</p>
                                    <h5 class="mt-2">Price: Rs {{ product.price}}</h5>
                                </div>
                                <div class="col-md-4">
                                    <a href="{% url 'seller:update_product' product.id %}" class="btn btn-outline-success m-2">Update</a>
                                    <a href="{% url 'seller:delete_product' product.id %}" class="btn btn-outline-danger m-2">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
                </div>
            </div>
        {% endfor %}        
    </div>
    
</div>

{% endblock body %}

templates/seller/categorized_seller_products.html
{% extends 'base.html' %}

{% load custom_tag %}

{% block body %}
    {% if request.user|has_group:"seller" %}
        <a href="{% url 'seller:create_products' %}" class="btn btn-outline-primary m-3">Add Product</a>
    {% endif %}
<div class="container">

    <div class="row">
        <div class="col-10">

        </div>
        <div class="col-2">
            <div class="dropdown mt-5">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                  Filter
                </button>
                <a class="btn btn-secondary" href="{% url 'seller:seller_products' %}">Clear</a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  <li><a class="dropdown-item" href="{% url 'seller:categorized_seller_products' 'electrical appliances' %}">Electrical Appliances</a></li>
                  <li><a class="dropdown-item" href="{% url 'seller:categorized_seller_products' 'clothes' %}">Clothes</a></li>
                  <li><a class="dropdown-item" href="{% url 'seller:categorized_seller_products' 'footwares' %}">Footwares</a></li>
                  <li><a class="dropdown-item" href="{% url 'seller:categorized_seller_products' 'home appliances' %}">Home Appliances</a></li>
                </ul>
              </div>
        </div>
    </div>

    <div class="row">
    <div class="text-center mb-5 mt-5"><h1>{{ category_name }}</h1></div>
        {% for product in all_products %}
            <div class="col-4">
                <div class="card" style="width: 18rem;">
                    <img src="{{ MEDIA_ROOT }}{{product.image.url}}" class="card-img-top" alt="..." width="150" height="250">
                    <div class="card-body text-center">
                        <h5 class="card-title">{{ product.name}}</h5>
                        <p class="card-text">Rs {{ product.price }}</p>
                        <a class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#test{{product.id}}" >View</a>
                    </div>
                </div>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="test{{product.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Product Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-8">
                                    <img src="{{ MEDIA_ROOT }}{{product.image.url}}" class="card-img-top" alt="..." width="150" height="250">
                                    <h4>{{ product.name}}</h4>
                                    <p>{{ product.description}}</p>
                                    <p>Category :{{ product.category }}</p>
                                    <h5 class="mt-2">Price: Rs {{ product.price}}</h5>
                                    {% if request.user|has_group:"buyer" %}
                                        <form method="POST" action="{% url 'seller:add_to_cart' product.id %}" class="mx-1 mx-md-4" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <input type="submit" value="Add To Cart" name="Add Product" class="btn btn-warning">
                                        </form>
                                    {% endif %}
                                </div>
                                <div class="col-md-4">
                                    {% if request.user|has_group:"seller" %}
                                        <a href="{% url 'seller:update_product' product.id %}" class="btn btn-outline-success m-2">Update</a>
                                        <a href="{% url 'seller:delete_product' product.id %}" class="btn btn-outline-danger m-2">Delete</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
                </div>
            </div>
        {% endfor %}        
    </div>
    
</div>

{% endblock body %}

templates/seller/product_confirm_delete.html
{% extends 'base.html' %}

{% block body %}

<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
  
                  <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Delete Product</p>
  
                  <form method="POST" action="" class="mx-1 mx-md-4" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="d-flex flex-row align-items-center mb-4">
                      <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                      <div class="form-outline flex-fill mb-0">
                          <label class="form-label" for="form3Example1c">Are you Sure ?</label>
                      </div>
                    </div>

                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                        <input type="submit" value="Delete Product" name="Delete Product" class="btn btn-outline-danger m-2">
                        <a class="btn btn-outline-warning m-2" href="{% url 'seller:seller_products' %}"> Cancel </a>
                    </div>
  
                  </form>


    
  
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
  
                  <img src="https://img.freepik.com/free-vector/online-shopping-concept-landing-page_52683-12876.jpg?size=626&ext=jpg&ga=GA1.2.204273489.1694169456&semt=ais"
                    class="img-fluid" alt="Sample image">
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>





{% endblock body %}

templates/seller/products.html
{% extends 'base.html' %}

{% load custom_tag %}

{% block body %}
    {% if request.user|has_group:"seller" %}
        <a href="{% url 'seller:create_products' %}" class="btn btn-outline-primary m-3">Add Product</a>
    {% endif %}
<div class="container">

    <div class="row">
        <div class="col-10">

        </div>
        <div class="col-2">
            <div class="dropdown mt-5">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                  Filter
                </button>
                <a class="btn btn-secondary" href="{% url 'seller:seller_products' %}">Clear</a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                    <li><a class="dropdown-item" href="{% url 'seller:categorized_seller_products' 'electrical appliances' %}">Electrical Appliances</a></li>
                    <li><a class="dropdown-item" href="{% url 'seller:categorized_seller_products' 'clothes' %}">Clothes</a></li>
                    <li><a class="dropdown-item" href="{% url 'seller:categorized_seller_products' 'footwares' %}">Footwares</a></li>
                    <li><a class="dropdown-item" href="{% url 'seller:categorized_seller_products' 'home appliances' %}">Home Appliances</a></li>
                </ul>
              </div>
        </div>
    </div>

    <div class="row">
    <div class="text-center mb-5 mt-5"><h1>Our Featured Products</h1></div>
        {% for product in all_products %}
            <div class="col-4">
                <div class="card mb-5" style="width: 18rem;">
                    <img src="{{ MEDIA_ROOT }}{{product.image.url}}" class="card-img-top" alt="..." width="150" height="250">
                    <div class="card-body text-center">
                        <h5 class="card-title">{{ product.name}}</h5>
                        <p class="card-text">Rs {{ product.price }}</p>
                        <a class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#test{{product.id}}" >View</a>
                    </div>
                </div>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="test{{product.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Product Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-8">
                                    <img src="{{ MEDIA_ROOT }}{{product.image.url}}" class="card-img-top" alt="..." width="150" height="250">
                                    <h4>{{ product.name}}</h4>
                                    <p>{{ product.description}}</p>
                                    <p>Category :{{ product.category }}</p>
                                    <h5 class="mt-2">Price: Rs {{ product.price}}</h5>
                                    {% if request.user|has_group:"buyer" %}
                                        <form method="POST" action="{% url 'seller:add_to_cart' product.id %}" class="mx-1 mx-md-4" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <input type="submit" value="Add To Cart" name="Add Product" class="btn btn-warning">
                                        </form>
                                    {% endif %}
                                </div>
                                <div class="col-md-4">
                                    {% if request.user|has_group:"seller" %}
                                        <a href="{% url 'seller:update_product' product.id %}" class="btn btn-outline-success m-2">Update</a>
                                        <a href="{% url 'seller:delete_product' product.id %}" class="btn btn-outline-danger m-2">Delete</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
                </div>
            </div>
        {% endfor %}        
    </div>
    
</div>

{% endblock body %}