authentication/urls.py
from django.urls import path

from authentication.views import (
    DefaultView,
    HomeView,
    LoginView,
    LogoutView,
    RegisterView,
)

app_name = 'authentication'

urlpatterns = [
    path('signup/', RegisterView.as_view(), name="signup"),
    path('home/', HomeView.as_view(), name="home"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('', DefaultView.as_view(), name="default"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('seller.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

seller/urls.py
from django.urls import path
from seller.views import (
    SellerProducts,
    SellerProductsCreateView,
    SellerProductDeleteView,
    SellerProductUpdateView,
    CategorizedSellerProductView,
    CartView,
    DeleteCartView,
    RemoveCartProductView,
)

app_name = "seller"

urlpatterns = [
    path("products/", SellerProducts.as_view(), name="seller_products"),
    path(
        "create-products/",
        SellerProductsCreateView.as_view(),
        name="create_products",
    ),
    path(
        "update-product/<uuid:pk>",
        SellerProductUpdateView.as_view(),
        name="update_product",
    ),
    path(
        "delete-product/<uuid:pk>",
        SellerProductDeleteView.as_view(),
        name="delete_product",
    ),
    path(
        "categorized-seller-products/<str:category>",
        CategorizedSellerProductView.as_view(),
        name="categorized_seller_products",
    ),
    path("add-to-cart/<uuid:id>", CartView.as_view(), name="add_to_cart"),
    path("cart/", CartView.as_view(), name="cart"),
    path("empty-cart/", DeleteCartView.as_view(), name="empty_cart"),
    path(
        "remove-product/<uuid:id>",
        RemoveCartProductView.as_view(),
        name="remove_product"
        ),
]

templates/base.html
{% load custom_tag %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Ecom Project</title>
    <style>

      .logo-image{
        width: 50px;
        height: 50px;
        border-radius: 50%;
        overflow: hidden;
        margin-top: -6px;
    }
    
    </style>
  </head>
  <body>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Ecom</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'authentication:home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'seller:seller_products' %}">Products</a>
            </li>
            <li class="nav-item dropdown">
              
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                
              </ul>
            </li>
            <li class="nav-item">
              
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success  " type="submit">Search</button>
          </form>
          {% if request.user.is_authenticated %}
            {% if request.user|has_group:"buyer" %}
              <a href="{% url 'seller:cart' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-cart3 m-3" viewBox="0 0 16 16">
                    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
              </a>
            {% endif %}
            <a href="{% url 'authentication:logout' %}" class="btn btn-outline-warning m-2">Log Out</a>
          {% else %}          
            <a href="{% url 'authentication:signup' %}" class="btn btn-outline-light m-2">Sign Up</a>
            <a href="{% url 'authentication:login' %}" class="btn btn-outline-light">Sign In</a>
          {% endif %}
        </div>
      </div>
      {% if request.user.is_authenticated %}
        <a class="navbar-brand" href="/">
          <div class="logo-image">
                {% if request.user.profile_image %}
                  <img src="{{ MEDIA_ROOT }}{{request.user.profile_image.url}}" alt="..." class="img-fluid">
                  {% else %}
                  <img src="https://cdn-icons-png.flaticon.com/512/219/219959.png" alt="..." class="img-fluid">
                {% endif %}
          </div>
        </a>
      {% endif %}
    </nav>

    <div class="container-fluid">
      {% block body %}
      {% endblock %}      
    </div>




    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load custom_tag %}

{% block body %}
<div class="row">
    <div class="col-11">
        <h2 class="text-center mt-3">Our Products</h2>
    </div>
    <div class="col-1">
        
    </div>
</div>
<div class="row">
    <div class="col-3">
        <h4 class="mt-5 mb-5 ms-2">Electrical Appliances</h4>
        {% for electrical in  electrical_appliances %}
            <div class="card mb-5" style="width: 18rem;">
                <img src="{{ MEDIA_ROOT }}{{ electrical.image.url }}" class="card-img-top" alt="..." width="150" height="250">
                <div class="card-body text-center">
                    <h5 class="card-title">{{ electrical.name}}</h5>
                    <p class="card-text">Rs {{ electrical.price }}</p>
                    <a class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#test{{electrical.id}}" >View</a>
                </div>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="test{{electrical.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Product Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-8">
                                    <img src="{{ MEDIA_ROOT }}{{electrical.image.url}}" class="card-img-top" alt="..." width="150" height="250">
                                    <h4>{{ electrical.name}}</h4>
                                    <p>{{ electrical.description}}</p>
                                    <p>Category :{{ electrical.category }}</p>
                                    <h5 class="mt-2">Price: Rs {{ electrical.price}}</h5>
                                    {% if user_type == 'BUYER' %}
                                        <form method="POST" action="{% url 'seller:add_to_cart' electrical.id %}" class="mx-1 mx-md-4" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <input type="submit" value="Add To Cart" name="Add Product" class="btn btn-warning">
                                        </form>
                                    {% endif %}
                                </div>
                                <div class="col-md-4">
                                    {% if request.user|has_group:"seller" %}
                                        <a href="{% url 'seller:update_product' electrical.id %}" class="btn btn-outline-success m-2">Update</a>
                                        <a href="{% url 'seller:delete_product' electrical.id %}" class="btn btn-outline-danger m-2">Delete</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="col-3">
        <h4 class="mt-5 mb-5 ms-2">Clothes</h4>
        {% for cloth in clothes %}
            <div class="card mb-5" style="width: 18rem;">
                <img src="{{ MEDIA_ROOT }}{{cloth.image.url}}" class="card-img-top" alt="..." width="150" height="250">
                <div class="card-body text-center">
                    <h5 class="card-title">{{ cloth.name}}</h5>
                    <p class="card-text">Rs {{ cloth.price }}</p>
                    <a class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#test{{cloth.id}}" >View</a>
                </div>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="test{{cloth.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Product Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-8">
                                    <img src="{{ MEDIA_ROOT }}{{cloth.image.url}}" class="card-img-top" alt="..." width="150" height="250">
                                    <h4>{{ cloth.name}}</h4>
                                    <p>{{ cloth.description}}</p>
                                    <p>Category :{{ cloth.category }}</p>
                                    <h5 class="mt-2">Price: Rs {{ cloth.price}}</h5>
                                    {% if user_type == 'BUYER' %}
                                        <form method="POST" action="{% url 'seller:add_to_cart' cloth.id %}" class="mx-1 mx-md-4" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <input type="submit" value="Add To Cart" name="Add Product" class="btn btn-warning">
                                        </form>
                                    {% endif %}
                                </div>
                                <div class="col-md-4">
                                    {% if user_type == 'SELLER' %}
                                        <a href="{% url 'seller:update_product' cloth.id %}" class="btn btn-outline-success m-2">Update</a>
                                        <a href="{% url 'seller:delete_product' cloth.id %}" class="btn btn-outline-danger m-2">Delete</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
                </div>
            </div>
        {% endfor %}
    </div>
    

    <div class="col-3">
        <h4 class="mt-5 mb-5 ms-2">Footwares</h4>
        {% for footware in footwares %}
            <div class="card mb-5" style="width: 18rem;">
                <img src="{{ MEDIA_ROOT }}{{footware.image.url}}" class="card-img-top" alt="..." width="150" height="250">
                <div class="card-body text-center">
                    <h5 class="card-title">{{ footware.name}}</h5>
                    <p class="card-text">Rs {{ footware.price }}</p>
                    <a class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#test{{footware.id}}" >View</a>
                </div>
            </div>
            
            <!-- Modal -->
            <div class="modal fade" id="test{{footware.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Product Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-8">
                                    <img src="{{ MEDIA_ROOT }}{{footware.image.url}}" class="card-img-top" alt="..." width="150" height="250">
                                    <h4>{{ footware.name}}</h4>
                                    <p>{{ footware.description}}</p>
                                    <p>Category :{{ footware.category }}</p>
                                    <h5 class="mt-2">Price: Rs {{ footware.price}}</h5>
                                    {% if user_type == 'BUYER' %}
                                        <form method="POST" action="{% url 'seller:add_to_cart' footware.id %}" class="mx-1 mx-md-4" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <input type="submit" value="Add To Cart" name="Add Product" class="btn btn-warning">
                                        </form>
                                    {% endif %}
                                </div>
                                <div class="col-md-4">
                                    {% if user_type == 'SELLER' %}
                                        <a href="{% url 'seller:update_product' footware.id %}" class="btn btn-outline-success m-2">Update</a>
                                        <a href="{% url 'seller:delete_product' footware.id %}" class="btn btn-outline-danger m-2">Delete</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="col-3">
        <h4 class="mt-5 mb-5 ms-2">Home Appliances</h4>
        {% for homeapp in home_appliances %}
            <div class="card mb-5" style="width: 18rem;">
                <img src="{{ MEDIA_ROOT }}{{homeapp.image.url}}" class="card-img-top" alt="..." width="150" height="250">
                <div class="card-body text-center">
                    <h5 class="card-title">{{ homeapp.name}}</h5>
                    <p class="card-text">Rs {{ homeapp.price }}</p>
                    <a class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#test{{homeapp.id}}" >View</a>
                </div>
            </div>
            
            <!-- Modal -->
            <div class="modal fade" id="test{{homeapp.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Product Details</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-8">
                                    <img src="{{ MEDIA_ROOT }}{{homeapp.image.url}}" class="card-img-top" alt="..." width="150" height="250">
                                    <h4>{{ homeapp.name}}</h4>
                                    <p>{{ homeapp.description}}</p>
                                    <p>Category :{{ homeapp.category }}</p>
                                    <h5 class="mt-2">Price: Rs {{ homeapp.price}}</h5>
                                    {% if user_type == 'BUYER' %}
                                        <form method="POST" action="{% url 'seller:add_to_cart' homeapp.id %}" class="mx-1 mx-md-4" enctype="multipart/form-data">
                                            {% csrf_token %}
                                            <input type="submit" value="Add To Cart" name="Add Product" class="btn btn-warning">
                                        </form>
                                    {% endif %}
                                </div>
                                <div class="col-md-4">
                                    {% if user_type == 'SELLER' %}
                                        <a href="{% url 'seller:update_product' homeapp.id %}" class="btn btn-outline-success m-2">Update</a>
                                        <a href="{% url 'seller:delete_product' homeapp.id %}" class="btn btn-outline-danger m-2">Delete</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
                </div>
            </div>
        {% endfor %}
    </div>

</div>



{% endblock body %}